del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc\props_common\common.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_gc\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_gc\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_gc\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_gc\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_gc\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_k8\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_k8\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_k8\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_k8\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_k8\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_nehalem\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_nehalem\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_nehalem\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_nehalem\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_nehalem\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_p3\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_p3\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_p3\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_p3\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_p3\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_sandybridge\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_sandybridge\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_sandybridge\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_sandybridge\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_sandybridge\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.pre.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_core2\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_cxx\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_cxx\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_cxx\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_cxx\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_cxx\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_gc\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_gc\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_gc\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_gc\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_gc\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_k8\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_k8\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_k8\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_k8\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_k8\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_nehalem\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_nehalem\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_nehalem\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_nehalem\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_nehalem\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_p3\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_p3\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_p3\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_p3\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_p3\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_sandybridge\project.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_sandybridge\project.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_sandybridge\project.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_sandybridge\project.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\lib_mpir_sandybridge\project.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.dll.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.lib.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.x64.props
