del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc\props_common\common.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\dll_mpir_core2.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\dll_mpir_core2.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\dll_mpir_core2.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\dll_mpir_core2.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\dll_mpir_core2\dll_mpir_core2.x64.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.debug.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.dll.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.lib.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.release.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.win32.props
del  e:\Working\MPIR_Work\mpir_msvc_config\build.vc12.p.handmade\_props\msvc120.x64.props
